### ISSUE TITLE
Impossible installation on Windows 8

### ISSUE THREAD

**Issue by Xartok** [FGRibreau/filesync#26] opened 2015-06-10 20:25 UTC
Hello, 

I tried to install filesync on my computer with `npm i filesync -g`
I got this output on my command prompt:

![npm error](https://puu.sh/ijWrF/188d5252d6.png)

I have bower installed globally.
My config:

Windows 8.1 x64
node v0.12.2

Please, can someone tell me it's easy to fix ?
Thanks. ^^

**Comment by FGRibreau** [comment] 2015-06-11 06:13
the issue is related with bower, check that bower was installed in node_modules, if so change the "postinstall" with "./node_modules/.bin/bower install" and send a PR (even if it should work the way it's currently written)

**Comment by Xartok** [comment] 2015-06-13 16:26
Ok thanks, I will do that

**Comment by FGRibreau** [comment] 2015-06-13 17:35
Fixed in #27

**Closed as completed** 2015-06-13 17:35 UTC
